# Numpy (Numerical Python)

### 1. 넘파이 설치 확인

In [16]:
import numpy as np
#print(np.__version__)# 버전 확인

### 2. 넘파이 배열 (ndarry) 생성과 속성 확인

In [17]:
a1 = np.array([1, 2, 3])
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)
        #ndim: 차원 개수, shape: 차원 크기를 튜플로)
a2 = np.array((1, 2, 3))
print(a2, type(a2), a2.ndim, a2.shape, a2.size)


[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> 1 (3,) 3


In [18]:
a3 = np.array([[1, 2, 3], [4, 5, 6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [19]:
a4 = np.array([1, 2, 3], dtype=float)
print(a4, type(a4), a4.dtype, a4.ndim, a4.shape, a4.size)
a5 = np.array([1, 2, 3], float)

[1. 2. 3.] <class 'numpy.ndarray'> float64 1 (3,) 3


In [20]:
a6 = np.array([1, 4, 5, '8'], int)
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)
a7 = np.array([1, 4, 5, "8"], int)

[1 4 5 8]
<class 'numpy.ndarray'> int64 1 (4,) 4


In [21]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]
np.array(test_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3. Indexing

In [22]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(d[0], d[1], d[2], d[-1], d[-2])

d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0][0]) # 배열명[행][열] 형태
print(d2[0, 0]) # 배열명[행, 열] 형태
print(d2[1, 1])
print(d2[1, -1])

d3 = np.arange(12).reshape(2, 2, 3)
print(d3[0][0][0]) # 배열명[면][행][열] 형태
print(d3[0, 0, 0]) # 배열명[면, 행, 열] 형태
print(d3[1, 1, 2])
print(d3[-1, -1, -1])
print(d3)

1 2 3 9 8
1
1
7
10
0
0
11
11
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [23]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


### 4. Slicing

In [24]:
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0]) # 0행만 슬라이싱
print(d2[0,:]) # 0행의 전체 열 슬라이싱
print(d2[:,:-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d2[::2,::2]) # 2행 2열 간격으로 전체 행과 열 슬라이싱

# 슬라이싱 요소값을 한꺼번에 변경
print(d2[::2, ::3])
d2[::2, ::3] = 30
print(d2)

# 전체 요소값을 한꺼번에 변경
d2[:,:] = -1
print(d2)

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]
[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [25]:
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)
print(d3[:, :-1, :-1])
print(d3[:, 1:, 1:])
print(d3[:, :, -1])
print(d3[:, -1, -1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


In [26]:
d2 = np.arange(1,11).reshape(2, -1)
print(d2)
d2[:, :] = -1
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### 5. Boolean Indexing

In [27]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data > 3)
print(data[data > 3])

# 2보다 크고 6보다 작은 요소만 추출
print(data[(data > 3) & (data < 6)])
# 짝수만 출력
print(data[data % 2 == 0])
# 평균보다 작은 값만 추출
print(data[data < data.mean()])

[ True  True  True False False False]
[4 6 7]
[4]
[4 6 2 0]
[3 2 0]


 ### 5-1. Fancy Indexing

In [28]:
f = np.array([4, 6, 7, 3, 2])
indexes = np.array([1, 2, 0, 2, 2, 2])
print(f[indexes])

f2 = np.array([[1, 4], [9, 16]])
x = np.array([0, 1, 1, 1, 0, 0])
y = np.array([0, 0, 0, 1, 1, 1])
f2[x, y]

[6 7 4 7 7 7]


array([ 1,  9,  9, 16,  4,  4])

### 6. 넘파이 배열의 정렬

In [31]:
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
print(sorted_numbers[::-1])

numbers.sort()
print(numbers)

arr2d=np.array([[5, 6, 7, 8],
                [4, 3, 2, 1],
                [10, 9, 12, 11]])
print(arr2d)

print(np.sort(arr2d))
print(np.sort(arr2d, axis=1))
print(np.sort(arr2d, axis=0))

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]
[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [32]:
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

[5 0 4 6 7 8 3 1 2]


In [33]:
# [연습 문제] 성적 순으로 출력 (내림차순)
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])

score_sorted_index = np.argsort(scores)[::-1]# 내림차순
print(score_sorted_index)
print(names[score_sorted_index])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


In [34]:
x = np.arange(1, 7).reshape(2, 3)
#print(x)
x + x
#print(x + x)
x + 2
#print(x + 2)
y = np.array([10, 20, 30])
x + y

array([[11, 22, 33],
       [14, 25, 36]])

In [35]:
# 넘파이 배열의 주요 연산 함수
array_01 = np.arange(1, 13).reshape(4, 3)
array_02 = np.arange(13, 25).reshape(4, 3)
ndarray = array_01 + array_02

print(ndarray)
# 넘파이 배열의 sum, mean, max, min을 축을 따라 구하는 함수
print(ndarray.sum(axis = None))
print(ndarray.mean(axis = None))
print(ndarray.max(axis = None))
print(ndarray.min(axis = None))

# 넘파이 배열 데이터 중 max, min의 값이 있는 index 반환
print(ndarray.argmax(axis = None))
print(ndarray.argmin(axis = None))

# 배열 내부의 모든 값이 참일 떄는 True, 하나라도 참이 아닐 경우에는 False를 반환
# and 조건을 전체 요소에 적용
print(ndarray.all(axis = None))
print(np.all(ndarray, axis = None))

print(np.all(ndarray < 3))

print(ndarray.any(axis = None))
print(np.any(ndarray, axis = None))

print(np.any(ndarray < 4))

[[14 16 18]
 [20 22 24]
 [26 28 30]
 [32 34 36]]
300
25.0
36
14
11
0
True
True
False
True
True
False


In [36]:
# 1. 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data))) # True

# 2. 두 배열이 완전히 동일한지 확인
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(np.all(arr1 == arr2)) # True (요소별 비교 후 전체 확인)

True
True
